---
  - name: "{{ user_for_sudo }}: Check passwordless sudo"
    become_user: root
    become: true
    ansible.builtin.file:
      path: "/etc/sudoers.d/90-{{ user_for_sudo }}-nopasswd"
      mode: 0440
      state: touch
      modification_time: preserve
      access_time: preserve
  - name: "{{ user_for_sudo }}: Enable passwordless sudo"
    become_user: root
    become: true
    ansible.builtin.lineinfile:
      dest: /etc/sudoers.d/90-{{ user_for_sudo }}-nopasswd
      regexp: "%{{ user_for_sudo }}"
      line: "{{ user_for_sudo }} ALL=(ALL) NOPASSWD: ALL"
      validate: visudo -cf %s
      state: present
