---
  - name: Adding PPA repositories
    become_user: root
    become: true
    ansible.builtin.apt_repository:
      repo: "{{ item }}"
      state: present
    with_items:
      - "{{ ppa_list }}"
