---
  - name: Ubuntu First Run
    hosts: all
    become: true
    tasks:
      - name: Set timezone to Africa/Johannesburg
        community.general.timezone:
          name: Africa/Johannesburg
        when: not ansible_date_time.tz == "SAST"
      - name: Generate en_US.UTF-8 locale
        locale_gen:
          name: en_US.UTF-8
          state: present
        when: not ansible_env.LANG == "en_US.UTF-8"
      - name: Set locale to en_US.UTF-8
        command: update-locale LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8
        when: not ansible_env.LANG == "en_US.UTF-8"
      - name: Check passwordless sudo for {{ ansible_user_id }}
        stat:
          path: "/etc/sudoers.d/90-{{ ansible_user_id }}-nopasswd"
        register: file_exists 
      - name: Configure passwordless sudo for {{ ansible_user_id }}
        file:
          path: "/etc/sudoers.d/90-{{ ansible_user_id }}-nopasswd"
          mode: 0440
          state: touch
        when: not file_exists.stat.exists
      - name: Enable passwordless sudo for {{ ansible_user_id }}
        lineinfile:
          dest: /etc/sudoers.d/90-{{ ansible_user_id }}-nopasswd
          state: present
          regexp: "%{{ ansible_user_id }}"
          line: "{{ ansible_user_id }} ALL=(ALL) NOPASSWD: ALL"
          validate: visudo -cf %s
        when: not file_exists.stat.exists
      - name: Add GIT PPA
        ansible.builtin.apt_repository:
          repo: ppa:git-core/ppa
          state: present
      - name: Add Neovim PPA
        ansible.builtin.apt_repository:
          repo: ppa:neovim-ppa/stable
          state: present
      - name: Add nodesource key
        ansible.builtin.apt_key:
          url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
          state: present
      - name: Add nodesource repository
        ansible.builtin.apt_repository:
          repo: deb https://deb.nodesource.com/node_17.x impish main
  - name: Ubuntu Kubernetes
    hosts: kubenodes
    become: true
    tasks:
      - name: Add GlusterFS PPA
        ansible.builtin.apt_repository:
          repo: ppa:gluster/glusterfs-9
          state: present
