---
  - name: Initial configuration of Ubuntu servers
    hosts: all
    tasks:
      - include_tasks: roles/system/tasks/region_setup.yml
        vars:
          timezone_for_os: "Africa/Johannesburg"
          locale_for_os: "en_US.UTF-8"
      - include_tasks: roles/apt/tasks/install_ppa.yml
        vars:
          ppa_list:
            - ppa:git-core/ppa
            - ppa:neovim-ppa/stable
      - include_tasks: roles/apt/tasks/install_apt_key.yml
        vars:
          key_list:
            - https://deb.nodesource.com/gpgkey/nodesource.gpg.key
      - include_tasks: roles/apt/tasks/install_deb_sources.yml
        vars:
          repo_list:
            - deb https://deb.nodesource.com/node_17.x impish main
      - name: Update all packages
        become_user: root
        become: true
        ansible.builtin.apt:
          upgrade: full
          update_cache: true
      - name: Install required packages
        become_user: root
        become: true
        ansible.builtin.apt:
          pkg:
            - build-essential
            - coreutils
            - curl
            - i2c-tools
            - imagemagick
            - indicator-cpufreq
            - jq
            - lm-sensors
            - logrotate
            - neofetch
            - neovim
            - nodejs
            - python3
            - python3-pip
            - socat
            - software-properties-common
            - tmux
            - zsh
            - zsh-antigen
          update_cache: true
          autoclean: true
          state: present
      - name: Remove obsolete packages
        become_user: root
        become: true
        ansible.builtin.apt:
          pkg:
            - snapd
            - vim
            - vim-tiny
          purge: true
          autoremove: true
          autoclean: true
          state: absent
      - name: Create user - binarymisfit
        become_user: root
        become: true
        ansible.builtin.user:
          name: binarymisfit
          groups: sudo
          shell: /usr/bin/zsh
          state: present
      - include_tasks: roles/users/tasks/configure-env.yml
        vars:
          user_to_configure: "{{ item }}"
        with_items:
          - root
          - binarymisfit
      - include_tasks: roles/system/tasks/ansible-pull.yml
  - name: Configure servers to run as kubernetes nodes
    hosts: kubenodes
    handlers:
      - name: Restart Haproxy
        become_user: root
        become: true
        ansible.builtin.service:
          name: haproxy
          state: restarted
    tasks:
      - include_tasks: roles/apt/tasks/install_apt_key.yml
        vars:
          key_list:
            - https://packages.cloud.google.com/apt/doc/apt-key.gpg
      - include_tasks: roles/apt/tasks/install_ppa.yml
        vars:
          ppa_list:
            - ppa:gluster/glusterfs-9
      - include_tasks: roles/apt/tasks/install_deb_sources.yml
        vars:
          repo_list:
            - deb https://apt.kubernetes.io/ kubernetes-xenial main
      - name: Install required packages
        become_user: root
        become: true
        ansible.builtin.apt:
          pkg:
            - glusterfs-server
            - haproxy
            - keepalived
            - kubeadm
            - kubectl
            - kubelet
          update_cache: true
      - name: Configure haproxy
        become_user: root
        become: true
        ansible.builtin.template:
          src: templates/etc_haproxy_cfg.j2
          dest: /etc/haproxy/haproxy.cfg
          mode: 0644
          owner: root
          group: root
        notify: Restart Haproxy
