---
  - name: Configure servers to run as kubernetes nodes
    hosts: kubenodes
    handlers:
        - name: Restart Haproxy
          become_user: root
          become: true
          ansible.builtin.service:
            name: haproxy
            state: restarted
    tasks:
      - include_tasks: roles/apt/tasks/install_apt_key.yml
        vars:
          key_list:
            - https://download.docker.com/linux/ubuntu/gpg
            - https://packages.cloud.google.com/apt/doc/apt-key.gpg
        tags:
          - kube
      - include_tasks: roles/apt/tasks/install_deb_sources.yml
        vars:
          repo_list:
            - deb https://download.docker.com/linux/ubuntu impish stable
            - deb https://apt.kubernetes.io/ kubernetes-xenial main
        tags:
          - kube
      - name: Install required packages
        become_user: root
        become: true
        ansible.builtin.apt:
          pkg:
            - haproxy
            - keepalived
            - kubeadm
            - kubectl
            - kubelet
          update_cache: true
        tags:
          - kube
      - name: "Install python packages"
        become_user: root
        become: true
        ansible.builtin.pip:
          name: "{{ pip_item }}"
        loop_control:
          loop_var: pip_item
        with_items:
          - docker
        tags:
          - kube
      - name: Configure haproxy
        become_user: root
        become: true
        ansible.builtin.template:
          src: templates/etc_haproxy_cfg.j2
          dest: /etc/haproxy/haproxy.cfg
          mode: 0644
          owner: root
          group: root
        notify: Restart Haproxy
        tags:
          - kube
  - name: Configure kubernetes master
    hosts: digikube1
    tasks:
      - name: Prepare images for kubeadm
        become_user: root
        become: true
        shell: kubeadm config images pull
        tags:
          - kube
          - master
      - name: Resetting kubeadm
        become_user: root
        become: true
        shell: kubeadm reset -f
        register: output
        tags:
          - kube
          - master
