---
  - name: Configure servers to run as kubernetes nodes
    hosts: kubenodes
    handlers:
        - name: Restart Haproxy
          become_user: root
          become: true
          ansible.builtin.service:
            name: haproxy
            state: restarted
    tasks:
      - include_tasks: roles/apt/tasks/install_apt_key.yml
        vars:
          key_list:
            - https://download.docker.com/linux/ubuntu/gpg
            - https://packages.cloud.google.com/apt/doc/apt-key.gpg
        tags:
          - kube
