---
  - name: Initial configuration of Ubuntu servers
    hosts: all
    tasks:
      - include_tasks: roles/system/tasks/region_setup.yml
        vars:
          timezone_for_os: "Africa/Johannesburg"
          locale_for_os: "en_US.UTF-8"
        tags:
          - setup
      - include_tasks: roles/apt/tasks/install_ppa.yml
        vars:
          ppa_list:
            - ppa:git-core/ppa
            - ppa:neovim-ppa/stable
        tags:
          - setup
      - include_tasks: roles/apt/tasks/install_apt_key.yml
        vars:
          key_list:
            - https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        tags:
          - setup
      - include_tasks: roles/apt/tasks/install_deb_sources.yml
        vars:
          repo_list:
            - deb https://deb.nodesource.com/node_17.x impish main
        tags:
          - setup
      - name: Update all packages
        become_user: root
        become: true
        ansible.builtin.apt:
          upgrade: full
          update_cache: true
        tags:
          - setup
      - name: Install required packages
        become_user: root
        become: true
        ansible.builtin.apt:
          pkg:
            - apt-transport-https
            - build-essential
            - ca-certificates
            - coreutils
            - curl
            - i2c-tools
            - imagemagick
            - indicator-cpufreq
            - jq
            - lm-sensors
            - logrotate
            - neofetch
            - neovim
            - nodejs
            - python3
            - python3-pip
            - python3-setuptools
            - socat
            - software-properties-common
            - tmux
            - virtualenv
            - zsh
            - zsh-antigen
          update_cache: true
          autoclean: true
          state: present
        tags:
          - setup
      - name: Remove obsolete packages
        become_user: root
        become: true
        ansible.builtin.apt:
          pkg:
            - snapd
            - vim
            - vim-tiny
          purge: true
          autoremove: true
          autoclean: true
          state: absent
        tags:
          - setup
      - name: Create user - binarymisfit
        become_user: root
        become: true
        ansible.builtin.user:
          name: binarymisfit
          groups: sudo
          shell: /usr/bin/zsh
          state: present
        tags:
          - setup
      - include_tasks: roles/users/tasks/configure-env.yml
        vars:
          user_to_configure: "{{ item }}"
        with_items:
          - root
          - binarymisfit
        tags:
          - setup
      - include_tasks: roles/system/tasks/ansible-pull.yml
        tags:
          - setup
