---
  - include_tasks: ../../apt/tasks/install_ppa.yml
    vars:
      ppa_list:
        - ppa:ansible/ansible
  - name: Install ansible packages
    become_user: root
    become: true
    ansible.builtin.apt:
      pkg:
        - ansible
      update_cache: true
  - name: Enable localhost for ansible 
    become_user: root
    become: true
    ansible.builtin.template: 
      src: templates/etc_ansible_hosts.j2
      dest: /etc/ansible/hosts
      owner: root
      group: root
      mode: 0644
  - name: Create ansible working directory
    become_user: root
    become: true
    ansible.builtin.file:
      path: "/var/lib/ansible/local"
      mode: 0751
      group: root
      owner: root
      state: directory
  - name: Install ansible cron
    become_user: root
    become: true
    ansible.builtin.template: 
      src: templates/etc_crond_ansible_pull.j2
      dest: /etc/cron.d/ansible_pull
      mode: 0644
      owner: root
      group: root
    vars:
      schedule: "*/15 * * * *"
      cron_user: root
      logfile: /var/log/ansible_pull.log
      workdir: /var/lib/ansible/local
      repo_url: https://github.com/BinaryMisfit/ansible-playbooks
  - name: Install ansible logrotate
    become_user: root
    become: true
    ansible.builtin.template: 
      src: templates/etc_logrotated_ansible_pull.j2
      dest: /etc/logrotate.d/ansible-pull 
      mode: 0644
      owner: root
      group: root
    vars:
      logfile: /var/log/ansible_pull.log

